### ISSUE TITLE
error when `registerElement("canvas", require("@nativescript/canvas").Canvas)`

### ISSUE THREAD

**Issue by bigmistqke** [SudoMaker/DOMiNATIVE#9]
In a `solidjs` + `dominative` + `nativescript` project I am trying to extend DOM with canvas-element with the following line: 
```jsx
import { render } from "@nativescript-community/solid-js";
import { Canvas } from "@nativescript/canvas";
import { Application } from "@nativescript/core";
import { document, registerElement } from "dominative";

registerElement("canvas", Canvas)

render(() => <canvas/>, document.body.firstElementChild);

const create = () => document;w

Application.run({ create });
```
I get the following error:
```
An uncaught Exception occurred on "main" thread.
Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
File: (file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:31:12)

StackTrace: 
Canvas(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:836:24)
	at SubView(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:67239:5)
	at Tweakable(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:67591:5)
	at Node(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86151:6)
	at ParentNode(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86441:23)
	at Element(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86654:6)
	at canvas(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86769:5)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86141:27)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86800:12)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:100:19)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:54:159)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:85418:25)
	at updateFn(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83190:17)
	at runUpdates(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83804:17)
	at createRoot(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83195:12)
	at render(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:85416:59)
	at ./app/index.js(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:54:73)
	at __webpack_require__(file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:28:33)
	at __webpack_exec__(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:195:39)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:196:318)
	at __webpack_require__.X(file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:124:21)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:196:47)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:201:3)
	at require(:1:266)


Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context

StackTrace:
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
File: (file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:31:12)

StackTrace: 
Canvas(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:836:24)
	at SubView(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:67239:5)
	at Tweakable(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:67591:5)
	at Node(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86151:6)
	at ParentNode(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86441:23)
	at Element(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86654:6)
	at canvas(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86769:5)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86141:27)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86800:12)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:100:19)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:54:159)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:85418:25)
	at updateFn(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83190:17)
	at runUpdates(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83804:17)
	at createRoot(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83195:12)
	at render(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:85416:59)
	at ./app/index.js(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:54:73)
	at __webpack_require__(file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:28:33)
	at __webpack_exec__(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:195:39)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:196:318)
	at __webpack_require__.X(file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:124:21)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:196:47)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:201:3)
	at require(:1:266)


Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6764)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: com.tns.NativeScriptException: Error calling module function 
Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
File: (file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:31:12)

StackTrace: 
Canvas(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:836:24)
	at SubView(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:67239:5)
	at Tweakable(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:67591:5)
	at Node(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86151:6)
	at ParentNode(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86441:23)
	at Element(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86654:6)
	at canvas(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86769:5)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86141:27)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86800:12)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:100:19)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:54:159)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:85418:25)
	at updateFn(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83190:17)
	at runUpdates(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83804:17)
	at createRoot(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83195:12)
	at render(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:85416:59)
	at ./app/index.js(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:54:73)
	at __webpack_require__(file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:28:33)
	at __webpack_exec__(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:195:39)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:196:318)
	at __webpack_require__.X(file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:124:21)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:196:47)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:201:3)
	at require(:1:266)


Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:685)
	at com.tns.Runtime.run(Runtime.java:677)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6759)
	... 9 more

```

What I tried:
- using different lowercased names (same error as above)
- using capitalized names (would error bc in solid capitalized jsx is considered a component)
- it would work sometimes in hmr, but if the project would be re-installed it would give the above error
- `registerElement("canvas", makeView(Canvas))` (same error as above)
- use `registerDOMElement` instead, get a similar error:

```
An uncaught Exception occurred on "main" thread.
Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
File: (file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:31:12)

StackTrace: 
Canvas(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:836:24)
	at Node(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86151:6)
	at ParentNode(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86441:23)
	at Element(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86654:6)
	at canvas(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86769:5)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86141:27)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86800:12)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:100:19)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:52:159)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:85418:25)
	at updateFn(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83190:17)
	at runUpdates(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83804:17)
	at createRoot(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83195:12)
	at render(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:85416:59)
	at ./app/index.js(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:52:73)
	at __webpack_require__(file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:28:33)
	at __webpack_exec__(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:193:39)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:194:318)
	at __webpack_require__.X(file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:124:21)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:194:47)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:199:3)
	at require(:1:266)


Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context

StackTrace:
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
File: (file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:31:12)

StackTrace: 
Canvas(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:836:24)
	at Node(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86151:6)
	at ParentNode(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86441:23)
	at Element(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86654:6)
	at canvas(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86769:5)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86141:27)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86800:12)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:100:19)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:52:159)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:85418:25)
	at updateFn(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83190:17)
	at runUpdates(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83804:17)
	at createRoot(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83195:12)
	at render(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:85416:59)
	at ./app/index.js(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:52:73)
	at __webpack_require__(file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:28:33)
	at __webpack_exec__(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:193:39)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:194:318)
	at __webpack_require__.X(file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:124:21)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:194:47)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:199:3)
	at require(:1:266)


Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6764)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: com.tns.NativeScriptException: Error calling module function 
Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
File: (file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:31:12)

StackTrace: 
Canvas(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:836:24)
	at Node(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86151:6)
	at ParentNode(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86441:23)
	at Element(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86654:6)
	at canvas(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86769:5)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86141:27)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:86800:12)
	at createElement(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:100:19)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:52:159)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:85418:25)
	at updateFn(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83190:17)
	at runUpdates(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83804:17)
	at createRoot(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:83195:12)
	at render(file:///data/data/org.nativescript.dominativesolid/files/app/vendor.js:85416:59)
	at ./app/index.js(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:52:73)
	at __webpack_require__(file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:28:33)
	at __webpack_exec__(file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:193:39)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:194:318)
	at __webpack_require__.X(file:///data/data/org.nativescript.dominativesolid/files/app/runtime.js:124:21)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:194:47)
	at (file:///data/data/org.nativescript.dominativesolid/files/app/bundle.js:199:3)
	at require(:1:266)


Error: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:685)
	at com.tns.Runtime.run(Runtime.java:677)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6759)
	... 9 more
```

**Comment by bigmistqke** [comment]
The issue appeared to be with the canvas implementation of canvas.

fix:
`@nativescript/canvas/Canvas/index.android.js` Line 30:
```js
  const activity = Utils.android.getApplicationContext(); // Add this line instead of the exisitng one
  this._canvas = new org.nativescript.canvas.TNSCanvas(activity, useCpu);
```
